server {
    listen 443 ssl;
    server_name exportsaathi.rikinparekh.in;

    ssl_certificate /etc/letsencrypt/live/exportsaathi.rikinparekh.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/exportsaathi.rikinparekh.in/privkey.pem;

    location / {
        root /home/ubuntu/ExportSaathi-AI-for-Bharat/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
    }
}

server {
    listen 80;
    server_name exportsaathi.rikinparekh.in;
    return 301 https://$host$request_uri;
}